name: vscode-ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1
      - name: 'setup node: ${{ matrix.node-version }} platform: ${{ matrix.os }}'
        uses: actions/setup-node@v1
        with:
          fetch-depth: 1
          node-version: ${{ matrix.node-version }}

      - name: setup linux
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo ">>> Started xvfb";
          wget https://apt.puppetlabs.com/puppet6-release-trusty.deb;
          sudo dpkg -i puppet6-release-trusty.deb;
          sudo apt-get update;
          sudo apt-get install pdk;
          pdk --version;
        if: runner.os == 'Linux'

      - name: setup macos
        run: |
          export HOMEBREW_NO_AUTO_UPDATE=1;
          brew install --cask puppetlabs/puppet/pdk;
          /opt/puppetlabs/pdk/bin/pdk --version;
        if: runner.os == 'macOS'

      - name: setup windows
        run: |
          choco install pdk
        if: runner.os == 'Windows'

      - name: Install psake
        shell: pwsh
        run: Install-Module psake -Force

      - name: npm install
        shell: pwsh
        run: |
          npm install -g vsce --silent;
          npm install --silent;

      - name: npm build
        shell: pwsh
        run: |
          invoke-psake -taskList 'build'

      - name: npm test
        env:
          BUILD_VERSION: '0.99.${{ github.event.number }}'
          VSCODE_BUILD_VERBOSE: true
          DISPLAY: ':99.0'
        shell: pwsh
        run: |
          npm test --silent

      - name: vsce package
        if: runner.os == 'Linux'
        env:
          BUILD_VERSION: '0.99.${{ github.event.number }}'
        shell: pwsh
        run: |
          invoke-psake -properties @{ packageVersion = $env:BUILD_VERSION } -tasklist bump
          mkdir artifacts
          vsce package --out artifacts/puppet-vscode-$env:BUILD_VERSION.vsix

      - name: upload vsix
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@master
        with:
          name: 'puppet-vscode'
          path: artifacts
